# Generated by Django 5.1 on 2024-11-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicosEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialidadMedico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicosespecialidad')),
            ],
        ),
    ]
