# Generated by Django 5.1.3 on 2024-11-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
