# Generated by Django 5.1.3 on 2024-11-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cita_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00'), (10, '19:00'), (11, '20:00'), (12, '21:00')]),
        ),
    ]
