# Generated by Django 5.1.3 on 2024-11-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cita_hora_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=12)),
                ('area', models.IntegerField(choices=[(0, 'Falta de seguimiento'), (1, 'Tiempos de espera prolongados'), (2, 'Fallos en el servicio'), (3, 'Cambio de términos y condiciones'), (4, 'Mala atención al cliente'), (5, 'Devoluciones'), (6, 'Desabasto'), (7, 'Otros')])),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
