# Generated by Django 5.1.3 on 2024-11-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_soporte_alter_cita_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('prescripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cita')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicosespecialidad')),
            ],
        ),
    ]
