# Generated by Django 5.1.3 on 2024-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registromedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='rut',
            field=models.CharField(default='SIN-RUT', max_length=12),
            preserve_default=False,
        ),
    ]
